# Analyzing borrowers’ risk of defaulting

The purpose of this report, in brief, is to analyze the data provided to see if certain factors can be used as predictors for an individual's ability to repay a loan. The factors in question are the number of children they have, their marital status, their monthly income, and the reason they are seeking for the loan.

## Open the data file and have a look at the general information. 

In [2]:
# Loading all the libraries
import pandas as pd

In [3]:
# Load the data
data = pd.read_csv('/credit_scoring_eng.csv') # reference the file here

FileNotFoundError: [Errno 2] No such file or directory: '/credit_scoring_eng.csv'

## Task 1. Data exploration

**Description of the data**
- `children` - the number of children in the family
- `days_employed` - work experience in days
- `dob_years` - client's age in years
- `education` - client's education
- `education_id` - education identifier
- `family_status` - marital status
- `family_status_id` - marital status identifier
- `gender` - gender of the client
- `income_type` - type of employment
- `debt` - was there any debt on loan repayment
- `total_income` - monthly income
- `purpose` - the purpose of obtaining a loan

In [3]:
# Let's see how many rows and columns our dataset has

print("Rows:", len(data.axes[0]))
print("Columns:", len(data.axes[1]))

Rows: 21525
Columns: 12


In [4]:
# let's print the first 50 rows

data.head(50)

children  days_employed  dob_years            education  education_id  \
0          1   -8437.673028         42    bachelor's degree             0   
1          1   -4024.803754         36  secondary education             1   
2          0   -5623.422610         33  Secondary Education             1   
3          3   -4124.747207         32  secondary education             1   
4          0  340266.072047         53  secondary education             1   
5          0    -926.185831         27    bachelor's degree             0   
6          0   -2879.202052         43    bachelor's degree             0   
7          0    -152.779569         50  SECONDARY EDUCATION             1   
8          2   -6929.865299         35    BACHELOR'S DEGREE             0   
9          0   -2188.756445         41  secondary education             1   
10         2   -4171.483647         36    bachelor's degree             0   
11         0    -792.701887         40  secondary education             1   
12         0            NaN         65  secondary education             1   
13         0   -1846.641941         54         some college             2   
14         0   -1844.956182         56    bachelor's degree             0   
15         1    -972.364419         26  secondary education             1   
16         0   -1719.934226         35  secondary education             1   
17         0   -2369.999720         33    bachelor's degree             0   
18         0  400281.136913         53  secondary education             1   
19         0  -10038.818549         48  SECONDARY EDUCATION             1   
20         1   -1311.604166         36  secondary education             1   
21         1    -253.685166         33  secondary education             1   
22         1   -1766.644138         24  secondary education             1   
23         0    -272.981385         21    bachelor's degree             0   
24         1  338551.952911         57  secondary education             1   
25         0  363548.489348         67  secondary education             1   
26         0            NaN         41  secondary education             1   
27         0    -529.191635         28    bachelor's degree             0   
28         1    -717.274324         26    bachelor's degree             0   
29         0            NaN         63  secondary education             1   
30         1  335581.668515         62  secondary education             1   
31         0   -1682.083438         47    primary education             3   
32         0   -4649.910832         34  SECONDARY EDUCATION             1   
33         0   -1548.637544         48  secondary education             1   
34         0   -4488.067031         35  secondary education             1   
35         0  394021.072184         68  secondary education             1   
36         0    -176.216688         33  secondary education             1   
37         0   -6448.810860         43    BACHELOR'S DEGREE             0   
38         0    -597.881827         25    bachelor's degree             0   
39         0    -650.587796         31    bachelor's degree             0   
40         0   -1030.362606         30  secondary education             1   
41         0            NaN         50  secondary education             1   
42         0   -1257.496190         20         some college             2   
43         0   -4375.681384         43         some college             2   
44         1   -1362.041728         26  SECONDARY EDUCATION             1   
45         1   -1039.451741         49  secondary education             1   
46         2   -2262.712304         37  secondary education             1   
47         1   -2689.137274         33    bachelor's degree             0   
48         0   -3341.067886         45  secondary education             1   
49         0   -1181.443228         54  secondary education             1   

        family_status  family_status_id gender    income_type  debt  \
0    

Some of the areas seem a bit odd at a quick glance.

Most of the "days_employed" values are negative, which for a measure of time does not make logical sense.

"education" has different types of formatting, though it seems like it should be covered by changing cases.

"purpose" seems like it should be classified since there are different wordings with a few distinct categories appearing most often ("home", "real estate", "wedding", "car", "education")

In [5]:
# Get info on data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 21525 entries, 0 to 21524
Data columns (total 12 columns):
children            21525 non-null int64
days_employed       19351 non-null float64
dob_years           21525 non-null int64
education           21525 non-null object
education_id        21525 non-null int64
family_status       21525 non-null object
family_status_id    21525 non-null int64
gender              21525 non-null object
income_type         21525 non-null object
debt                21525 non-null int64
total_income        19351 non-null float64
purpose             21525 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.0+ MB


Some of the columns, 'days_employed' and 'total_income' are the ones with missing values.

In [6]:
# Let's look at the filtered table with missing values in the the first column with missing data

print(data.isna().sum())
print(data.isnull().sum()/ data.shape[0] * 100)

children               0
days_employed       2174
dob_years              0
education              0
education_id           0
family_status          0
family_status_id       0
gender                 0
income_type            0
debt                   0
total_income        2174
purpose                0
dtype: int64
children             0.000000
days_employed       10.099884
dob_years            0.000000
education            0.000000
education_id         0.000000
family_status        0.000000
family_status_id     0.000000
gender               0.000000
income_type          0.000000
debt                 0.000000
total_income        10.099884
purpose              0.000000
dtype: float64


Our missing values are the same size and they may be related categories (employment and income). It most likely is that these missing values are for people who are currently not working and thus would not be able to fill in either. However, there is no guarantee that they are not simply missing data points.

In [7]:
# Let's apply multiple conditions for filtering data and look at the number of rows in the filtered table.

cols_with_na = ['days_employed', 'total_income']
missing_values = []

for column in cols_with_na:
    subset = data[data[column].isna()]

subset.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 2174 entries, 12 to 21510
Data columns (total 12 columns):
children            2174 non-null int64
days_employed       0 non-null float64
dob_years           2174 non-null int64
education           2174 non-null object
education_id        2174 non-null int64
family_status       2174 non-null object
family_status_id    2174 non-null int64
gender              2174 non-null object
income_type         2174 non-null object
debt                2174 non-null int64
total_income        0 non-null float64
purpose             2174 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 220.8+ KB


**Intermediate conclusion**

There are 2174 rows in the table which is the same as the number of missing values on both days_employed and total_income. Since it is exactly the same, this also says that there are no values missing only one of the two values. Thus, it can be generally believed that these entries are representative of people who are not currently employed.

These points comprise roughly 10.1% of the data set. While it seems extremely large, it could be negligible if the data set itself is sufficiently large. However, it always would be preferable to fill missing values if there is a good way to do so.

In this case, the days_employed and total_income are likely strong data to work with when performing analysis relating to loans, so they should probably be filled out. However, there may not be an elegant way to do so with the given data set, as the most clear predictors for such things (age, education, marital status) may not necessarily be able to form a whole model for such a complicated topic.

Next, it would be auspicious to take a look over the subset and see if there are points that could be given a filler value of 0.0 indicating someone who is not simply in between jobs or who may simply be missing data for an unrelated reason. Students, spouses, and retirees would make the most sense to give this value. If they compose a sufficient portion of the data set, we could then make a decision on whether or not to drop the remaining values.

Since the questions we are trying to answer are pertaining primarily to **income level**, **marital status**, **number of children** and **history of repaying loans**, those will be given focus.

In [8]:
# Let's investigate clients who do not have data on identified characteristic and the column with the missing values

retirees = subset['income_type'].value_counts()

married = subset['family_status'].value_counts()

child = subset['children'].value_counts()

history = subset['debt'].value_counts()

print(retirees, end='\n\n')

print(child, end='\n\n')

print(married, end='\n\n')

print(history)

employee         1105
business          508
retiree           413
civil servant     147
entrepreneur        1
Name: income_type, dtype: int64

 0     1439
 1      475
 2      204
 3       36
 20       9
 4        7
-1        3
 5        1
Name: children, dtype: int64

married              1237
civil partnership     442
unmarried             288
divorced              112
widow / widower        95
Name: family_status, dtype: int64

0    2004
1     170
Name: debt, dtype: int64


In [9]:
# Checking distribution

ratio_by_income = retirees / len(subset)
ratio_by_marital = married / len(subset)
ratio_by_kid = child / len(subset)
ratio_by_history = history / len(subset)

print(ratio_by_income, end='\n\n')

print(ratio_by_kid, end='\n\n')

print(ratio_by_marital, end='\n\n')

print(ratio_by_history)

employee         0.508280
business         0.233671
retiree          0.189972
civil servant    0.067617
entrepreneur     0.000460
Name: income_type, dtype: float64

 0     0.661914
 1     0.218491
 2     0.093836
 3     0.016559
 20    0.004140
 4     0.003220
-1     0.001380
 5     0.000460
Name: children, dtype: float64

married              0.568997
civil partnership    0.203312
unmarried            0.132475
divorced             0.051518
widow / widower      0.043698
Name: family_status, dtype: float64

0    0.921803
1    0.078197
Name: debt, dtype: float64


**Possible reasons for missing values in data**

Looking over some of the data with missing values, there could be some good ways to fill out some of the missing data. Looking quickly over the data, there are at 413 values that are missing value because their income_type is listed as 'retiree'. This makes sense, as they are retired, that means they would not be employed and as a result not have an income. There may be other factors involved, such as if someone is getting married and will not be working in the future, or is in between jobs, applying for college loans, etc.

Additionally, there is 1 entrepreneur who naturally does not possess a fixed income or employment duration out of uncertainty so that entry should probably be safe to drop.

Married people make up 1237 rows, although there is naturally overlap with employment.

For some who are on the younger end of the data, such as below age 23, a good number do appear to be pursuing education which could mean they do not hold a job and thus they would not have either of the values present. However, there also are 10 entries who have dob_years = 0, which holds for simple incomplete information. Since there are only 10 of them, I will drop those entries whose age is listed as 0.

Those with 0 children, or fewer than 2 children, make up most of the entries which are missing income data. This does make sense under a similar assumption to before - those who are in pursuit of their education are more likely to have fewer children, if any.

To check if the missing values are caused by random chance, a simple measure will be taken. We will take our prior ratios, the ones made by using our NULL data set, and create a second ratio based on the data set without including rows with null values, and subtract the first ratios from the second.

If the result of this calculation is close to zero, then that means that the ratios we see in the null data set appear in roughly the same ratios as those in the data that has complete values. What this means, in brief, is that the missing data can be assumed as to have resulted from random chance. If, however, there is a significant difference between the two, that would suggest that perhaps there was a specific issue that caused a factor to have more missing data.

In [10]:
# Checking the distribution in the whole dataset

ratio_data = data.dropna()

ratio_by_job = (ratio_data['income_type'].value_counts()) / len(ratio_data)
ratio_by_family = (ratio_data['family_status'].value_counts()) / len(ratio_data)
ratio_by_child = (ratio_data['children'].value_counts()) / len(ratio_data)
ratio_by_debt = (ratio_data['debt'].value_counts()) / len(ratio_data)

print(ratio_by_job, end='\n\n')

print(ratio_by_family, end='\n\n')

print(ratio_by_child, end='\n\n')

print(ratio_by_debt, end='\n\n')


print("Difference in ratios of completed data and data with null values:")
print(ratio_by_job - ratio_by_income, end='\n\n')

print(ratio_by_family - ratio_by_marital, end='\n\n')

print(ratio_by_child - ratio_by_kid, end='\n\n')

print(ratio_by_debt - ratio_by_history)

employee                       0.517493
business                       0.236525
retiree                        0.177924
civil servant                  0.067800
unemployed                     0.000103
paternity / maternity leave    0.000052
student                        0.000052
entrepreneur                   0.000052
Name: income_type, dtype: float64

married              0.575836
civil partnership    0.193013
unmarried            0.130484
divorced             0.055966
widow / widower      0.044701
Name: family_status, dtype: float64

 0     0.656814
 1     0.224433
 2     0.095654
 3     0.015193
 20    0.003462
-1     0.002274
 4     0.001757
 5     0.000413
Name: children, dtype: float64

0    0.918816
1    0.081184
Name: debt, dtype: float64

Difference in ratios of completed data and data with null values:
business                       0.002855
civil servant                  0.000183
employee                       0.009213
entrepreneur                  -0.000408
paternity / mate

**Intermediate conclusion**

For the most part, the ratios being so similar in both the non-null and null data sets does suggest that most of the null values are null through random chance. However, there are some entries that have a fairly large discrepancy, that mean that the null values may be connected.

The ratio is 1% higher for retirees in the null set than the full set, which makes sense on an instinctual level. There also are 0.8% fewer employees in the null set, which signals that it is more likely an employee will have these data points represented in the full set. Additionally, the full set has parental leave, student, and unemployed values represented that are not present in the null set, but each of them comprises less than 0.0001 of the total data.

Married and civil partnership also seem to have a difference shown, but I do not believe that it is significant enough to make a difference, especially since they could display similar financial statuses in practice. If someone is living with a significant other, they may or may not be working.

Those with 0 children are slightly less common in the full set and those with 1 child are slightly more common in the null set. If we assume that 0 children is more likely to be a student, this would make sense. 1 child could be simply random chance, but there is a plausible explanation in that one could interpolate that as a family goes from 1, to 2, or more children, the more likely there is that one of the parents stays at home (which seems to line up with the data).

The difference in debt appears to be is more or less arbitrary. Someone may be less likely to acquire certain jobs if they have poor credit but as a whole credit should not have an impact on one's ability to find employment. There is only a 0.2686% difference between the sets.

We do not believe that some of these more complicated explanations should immediately be used on our data set when clearing up ones that may be less random such as retirees could give the total analysis more clarity later.

We have some leads, but it is not unreasonable to say that it is too soon to make conclusions. Quickly going over the remaining factors, we receive the following:

In [11]:
# Check for other reasons and patterns that could lead to missing values

edu_1 = subset['education'].value_counts() / len(subset)
edu_2 = ratio_data['education'].value_counts() / len(ratio_data)
edu_1 = subset['education'].value_counts() / len(subset)
edu_2 = ratio_data['education'].value_counts() / len(ratio_data)
gen_1 = subset['gender'].value_counts() / len(subset)
gen_2 = ratio_data['gender'].value_counts() / len(ratio_data)
debt_1 = subset['debt'].value_counts() / len(subset)
debt_2 = ratio_data['debt'].value_counts() / len(ratio_data)

print(edu_2 - edu_1, end='\n\n')

print(edu_2 - edu_1, end='\n\n')

print(gen_2 - gen_1, end='\n\n')

print(debt_2 - debt_1)

BACHELOR'S DEGREE      0.002391
Bachelor's Degree      0.001058
GRADUATE DEGREE             NaN
Graduate Degree             NaN
PRIMARY EDUCATION      0.000367
Primary Education      0.000263
SECONDARY EDUCATION    0.005613
SOME COLLEGE          -0.002083
Secondary Education    0.003484
Some College          -0.001153
bachelor's degree     -0.009971
graduate degree             NaN
primary education      0.003198
secondary education   -0.009858
some college           0.006379
Name: education, dtype: float64

BACHELOR'S DEGREE      0.002391
Bachelor's Degree      0.001058
GRADUATE DEGREE             NaN
Graduate Degree             NaN
PRIMARY EDUCATION      0.000367
Primary Education      0.000263
SECONDARY EDUCATION    0.005613
SOME COLLEGE          -0.002083
Secondary Education    0.003484
Some College          -0.001153
bachelor's degree     -0.009971
graduate degree             NaN
primary education      0.003198
secondary education   -0.009858
some college           0.006379
Name: e

**Conclusions**

The strongest possible connection here is an apparent slightly higher amount of females in the data set with missing values, but not by much. This could suggest a possible pattern but a weak one, if any. It is likely to still be random, as there are generally more females in the data set as a whole.

In some categories, missing values could be filled in with 0, since in some cases we can assume that the employment status (and, by extension, the total income) is 0. Students and employees, most obviously. For the remaining missing values. However, that may not be an ideal solution, and instead checking these values based on observed values would be more effective. For that, firstly, cleaning up data to make it more useable is important. Duplicates should be removed, data that is strikingly strange where it clearly is an error should be removed, columns should be normalized as much as possible. After the data has been cleaned, it will be in a state where it can be analyzed.

## Data transformation

As we can see in some of our earlier analysis, there are different formats for capitalization for the education status. Fortunately, it is all simply a capitalization issue, there could have been many more format differences (i.e. it could have an entry of "bachelors degree", or "grade school" which would require a little more than a simple change of case). Those will be fixed now.

In [12]:
# Let's see all values in education column to check if and what spellings will need to be fixed
data['education'].unique()

array(["bachelor's degree", 'secondary education', 'Secondary Education',
       'SECONDARY EDUCATION', "BACHELOR'S DEGREE", 'some college',
       'primary education', "Bachelor's Degree", 'SOME COLLEGE',
       'Some College', 'PRIMARY EDUCATION', 'Primary Education',
       'Graduate Degree', 'GRADUATE DEGREE', 'graduate degree'],
      dtype=object)

In [13]:
# Fix the registers if required
data['education'] = data['education'].str.lower()

In [14]:
# Checking all the values in the column to make sure we fixed them

data['education'].unique()

array(["bachelor's degree", 'secondary education', 'some college',
       'primary education', 'graduate degree'], dtype=object)

It was also seen before that there are strange inputs within the 'children' column that will be amended.

In [15]:
# Let's see the distribution of values in the `children` column
data['children'].value_counts()

 0     14149
 1      4818
 2      2055
 3       330
 20       76
-1        47
 4        41
 5         9
Name: children, dtype: int64

There are exactly 76 entries in the data set that have been assigned 20 as their number of children. It is probably safe to assume that these values are meant to be 2. By the same logic, the 47 entries of children marked as -1 are likely meant to be 1.

In [16]:
# [fix the data based on your decision]
data[data['children'] == -1] = 1
data[data['children'] == 20] = 2

In [17]:
# Checking the `children` column again to make sure it's all fixed

data['children'].value_counts()

0    14149
1     4865
2     2131
3      330
4       41
5        9
Name: children, dtype: int64

The main issue in the days_employed column is clearly having many negative values, which should not normally be possible. There also is one entry in the first few rows that are extremely massive. For instance, on row 4 there is an entry with 340266.072047 days employed, which would amount to approximately 932 years. Suffice to say, it's unlikely that anyone could have worked that long.

To search for sufficiently large days_employed, there are different ways we could tackle this, but with little information a simple benchmark could be to simply look at those who have been employed for a time greater than they could possibly be working. For the purpose of getting a quick look, a test will be run to see if, assuming the worker began employment at age 16 (very generous). We can also test for a couple other values - it is certainly possible that the metric of working for "their entire life starting from 16".

In [18]:
# Find problematic data in `days_employed`, if they exist, and calculate the percentage
days_cutoff = data[data['days_employed'] > (((data['dob_years'] - 16) * 365))]
days_no_cutoff = data[data['days_employed'] <= (((data['dob_years'] - 16) * 365))]

print("Employed days that are negative:\n",
      data[data['days_employed'] < 0]['days_employed'].count(), end='\n\n')

print("Employed days that are higher than the cutoff:\n",
      days_cutoff['days_employed'].count())
print("Employed days that are higher than 10,000 (approximately 27 years):\n",
     data[data['days_employed'] > 10000]['days_employed'].count())
print("Employed days that are higher than 18,000 (approximately 49 years):\n",
     data[data['days_employed'] > 18000]['days_employed'].count())
print("Employed days that are higher than 20,000 (approximately 55 years):\n",
     data[data['days_employed'] > 20000]['days_employed'].count())
print("Employed days that are higher than 100,000:\n",
     data[data['days_employed'] > 100000]['days_employed'].count(), end='\n\n')

print(f"Mean of the cutoff days: {days_cutoff['days_employed'].mean()}")
print(f"Median of the cutoff days: {days_cutoff['days_employed'].median()}", end='\n\n')

print(f"Mean of the non-cutoff days: {days_no_cutoff['days_employed'].mean()}")
print(f"Median of the non-cutoff days: {days_no_cutoff['days_employed'].median()}")

Employed days that are negative:
 15809

Employed days that are higher than the cutoff:
 3622
Employed days that are higher than 10,000 (approximately 27 years):
 3431
Employed days that are higher than 18,000 (approximately 49 years):
 3431
Employed days that are higher than 20,000 (approximately 55 years):
 3431
Employed days that are higher than 100,000:
 3431

Mean of the cutoff days: 345744.17191529745
Median of the cutoff days: 362889.81787920685

Mean of the non-cutoff days: -2356.2823155591896
Median of the non-cutoff days: -1632.8080131103472


These sections are mutually exclusive (one is negative, one is sufficiently large) so we can witness that over 90% of our data set has an issue with the days_employed column. It would be a good idea to examine the way that the data was gathered if a process will be repeated in the future, but at the moment cleaning it is our priority.

For the negative values, those are obvious and we only need to turn them positive. For the extremely large values of days_employed, we can witness that there are fewer values in the 10,000+ categories. There may be people who have been working for their entire life -16 years, and there also may be people who have been employed for many decades. By the time we reach a little over 15,000 days, the numbers begin to taper off and by the time we reach 20,000 days, all the values are also higher than 100,000. Most of them gather around a mean and median that both are approximately 336,000 days.

Thus, for the sufficiently large values, I would posit that the issue that any value with 6 digits has most likely been shifted by two figures. If we look at the values of the data that falls outside of the cutoff, the mean and median are around 2300 and 1600, respectively. This means that most of the people clearly do not reach 10,000 days of employment, and thus, it makes sense to alter values that have been employed for over 100,000 days into a four-digit value.

In [19]:
# Address the problematic values, if they exist

def make_positive(value):
    if value < 0:
        return (value * -1)
    return value

def significant_figures(value):
    if value > 20000:
        return (value / 100)
    return value

data['days_employed'] = data['days_employed'].apply(make_positive)
data['days_employed'] = data['days_employed'].apply(significant_figures)

In [20]:
# Check the result - make sure it's fixed
days_cutoff = data[data['days_employed'] > (((data['dob_years'] - 16) * 365))]
print(days_cutoff.pivot_table(index='days_employed', values = 'dob_years', aggfunc='count', margins=True))

print("Employed days that are negative:\n",
      data[data['days_employed'] < 0]['days_employed'].count())
print("Employed days that are higher than 20,000 (approximately 55 years):\n",
     data[data['days_employed'] > 20000]['days_employed'].count(), end='\n\n')

print(f"Mean of the days employed: {data['days_employed'].mean()}")
print(f"Median of the days employed: {data['days_employed'].median()}")

                    dob_years
days_employed                
1.0                        47
2.0                        76
108.96704186614716          1
162.9369524996826           1
176.40448651346043          1
...                       ...
16264.699500887124          1
16593.472817263817          1
17615.563265627912          1
18388.949900568383          1
All                       304

[184 rows x 1 columns]
Employed days that are negative:
 0
Employed days that are higher than 20,000 (approximately 55 years):
 0

Mean of the days employed: 2568.463235896076
Median of the days employed: 2169.312880287869


There still are 304 values that may seem odd to leave in, that have the person working for their entire life after 16 years of age. Be that as it may, many of them appear to be within plausible standards (ranging from a little over 100 days to the highest values of around 16-18 thousand days, or 43-49 years).

The majority of these values that remain in the "cutoff" segment, however, are 1 or 2 days of employment. They comprise 123 of the 304 values. On an instinctual level, this seems strange, especially when the way the cutoff was made was by assuming the days employed was higher than the person's days since their 16th birthday. Unless there are a lot of people in the data set who are 16 years old and getting their data collected 1 or 2 days after taking employment, these data points might seem fishy.

Also, it somewhat connects to one of the issues we have identified before, that there are some people who have a birth year of 0.

Next, let's look at the age values.

In [21]:
# Check the `dob_years` for suspicious values and count the percentage

print(data['dob_years'].value_counts())
print(f"Mean age: {data['dob_years'].mean()}")
print(f"Median age: {data['dob_years'].median()}", end='\n\n')

print(data[data['dob_years'] == 0]['purpose'].unique())
print(data[data['dob_years'] == 1]['purpose'].unique())
print(data[data['dob_years'] == 2]['purpose'].unique())

35    614
40    603
41    603
34    597
38    595
42    592
33    577
39    572
31    556
36    553
29    543
44    543
48    536
30    536
37    531
43    510
50    509
32    506
49    505
28    501
45    494
27    490
52    483
56    482
47    480
54    476
46    469
58    461
53    457
57    457
51    446
55    441
59    441
26    406
60    376
25    356
61    353
62    351
63    268
64    263
24    263
23    252
65    194
66    183
22    183
67    167
21    110
0     100
68     99
69     83
2      76
70     65
71     58
20     51
1      47
72     33
19     14
73      8
74      6
75      1
Name: dob_years, dtype: int64
Mean age: 43.06202090592335
Median age: 42.0

['car' 'housing transactions' 'housing renovation'
 'construction of own property' 'to own a car' 'buy real estate'
 'to get a supplementary education' 'purchase of a car' 'housing'
 'to buy a car' 'real estate transactions' 'property' 'to have a wedding'
 'buying my own car' 'cars' 'buy residential real estate'
 'wedding 

There are three sections in the years data set that are obvious issues: the 76 with age 2, the 47 with age 1, and the 100 with age 0. At a cursory glance, it appears that the values that have 0 as the age are ones that had some sort of issue, but the ones with values 1 and 2 are bad data points that have their entire row filled up with their respective value.

By taking a look at the 'purpose' column for unique values, this becomes more apparent. The set of age = 0 has distinct purposes filled out, whereas the ages 1 and 2 have their purposes being listed as "1" and "2", which signals that there are not any points in that data set that aren't rows of 1 and 2.

So, for the 1 and 2 data points, those should be removed entirely. For age = 0, we could simply assign the median age of 42 (which is close to the mean age of 43). It may be possible to try and determine the age based on values in other columns since we have access to mean/median for the average amount of days employed and could possibly use that coupled with something like education status, number of children, and marital status to attempt and approximate the age of the subject in question. We also could mark the age as unknown, though that could make working with the data more difficult.

Since there are 100 points with age = 0, which comprises approximately 0.47% of our data set (even after removing the 1 and 2 points), it generally would be easier and cause less issues in this instance to remove them.

In [22]:
# Address the issues in the `dob_years` column, if they exist
data = data[data['dob_years']>2]

In [23]:
# Check the result - make sure it's fixed
data[data['dob_years'] <= 2].count()

children            0
days_employed       0
dob_years           0
education           0
education_id        0
family_status       0
family_status_id    0
gender              0
income_type         0
debt                0
total_income        0
purpose             0
dtype: int64

The family status column may have some issues, but since there are no null values and we have witnessed that there are 5 categories of family status, there should be little issue. The only problem that could arise is if the family_status_id column does not match with the status' categorical descriptor.

In [24]:
# Let's see the values for the column

data.groupby('family_status')['family_status_id'].value_counts()

family_status      family_status_id
civil partnership  1                    4139
divorced           3                    1179
married            0                   12254
unmarried          4                    2783
widow / widower    2                     947
Name: family_status_id, dtype: int64

We can confirm that simply, there is no mismatch between the family_status and family_status_id. Thus, there is no issue here.

The gender column is easier. We know there are no empty values so all we need to do is see if there are unexpected values (which would tend to be ones not listed as M or F.)

In [25]:
# Let's see the values in the column
data['gender'].value_counts()

F      14083
M       7218
XNA        1
Name: gender, dtype: int64

In [26]:
# Address the problematic values, if they exist
data[data['gender'] == 'XNA']

children  days_employed  dob_years     education  education_id  \
10701         0    2358.600502         24  some college             2   

           family_status  family_status_id gender income_type  debt  \
10701  civil partnership                 1    XNA    business     0   

       total_income          purpose  
10701     32624.825  buy real estate

There is one gender that is listed as 'XNA'. This most likely is just an unknown value, and if necessary we would replace it with an unknown value. If we need to analyze based on gender, since we don't have any particular way to determine this, then dropping this row would be fine. However, there is no need to remove it at the moment.

One other thing that seems like we might be dealing with some sort of skewed data is that there are twice as many female entries as there are men. Most people would assume that female and male should be approximately equal. We have no reason to believe that these female entries might be misattributed. It is possible that there is some cause in the data collection process that makes women more likely to be represented.

The column for 'income_type' also should not be a column with notable issues. We have gotten a look at the types of income earlier in this project and did not see a significantly strange result.

In [27]:
# Let's see the values in the column
data['income_type'].value_counts()

employee                       10996
business                        5034
retiree                         3819
civil servant                   1447
unemployed                         2
entrepreneur                       2
student                            1
paternity / maternity leave        1
Name: income_type, dtype: int64

If we needed to, it would be possible to truncate the values into fewer columns (such as counting parental leave as 'employee' or entrepreneurship as 'business'). The distinction between 'employee', 'business' and 'civil servant' seems a bit arbitrary and they might all be considered to be similar in nature, but without a more detailed description we are not equipped make any judgments on such a thing.

Since there is no clear need to, the column will remain unchanged.

Now we can check for duplicate entries. Due to the columns of 'days_employed', 'total_income', and 'purpose' being highly specific, it is likely that there won't be many duplicated rows that aren't mistakes. Though also it is possible that there may be some duplicated lines that had a different 'education' status that now are duplicates since we have made all the entries in that column lower case.

In [28]:
# Checking duplicates

data[data.duplicated()].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 71 entries, 2849 to 21415
Data columns (total 12 columns):
children            71 non-null int64
days_employed       0 non-null float64
dob_years           71 non-null int64
education           71 non-null object
education_id        71 non-null int64
family_status       71 non-null object
family_status_id    71 non-null int64
gender              71 non-null object
income_type         71 non-null object
debt                71 non-null int64
total_income        0 non-null float64
purpose             71 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 7.2+ KB


In [29]:
# Address the duplicates, if they exist
data = data.drop_duplicates()

In [30]:
# Last check whether we have any duplicates
data[data.duplicated()].info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 0 entries
Data columns (total 12 columns):
children            0 non-null int64
days_employed       0 non-null float64
dob_years           0 non-null int64
education           0 non-null object
education_id        0 non-null int64
family_status       0 non-null object
family_status_id    0 non-null int64
gender              0 non-null object
income_type         0 non-null object
debt                0 non-null int64
total_income        0 non-null float64
purpose             0 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 0.0+ bytes


In [31]:
# Check the size of the dataset that you now have after your first manipulations with it
data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 21231 entries, 0 to 21524
Data columns (total 12 columns):
children            21231 non-null int64
days_employed       19150 non-null float64
dob_years           21231 non-null int64
education           21231 non-null object
education_id        21231 non-null int64
family_status       21231 non-null object
family_status_id    21231 non-null int64
gender              21231 non-null object
income_type         21231 non-null object
debt                21231 non-null int64
total_income        19150 non-null float64
purpose             21231 non-null object
dtypes: float64(2), int64(5), object(5)
memory usage: 2.1+ MB


Most of the changes done in this case were making things more consistent in formatting. We have lost a small amount of our missing values. They used to represent 10.0999% of our data set, but now are 9.8017%. As a whole, the data set has not been made into a final state but it is now completely workable.

# Working with missing values

### Restoring missing values in `total_income`

As we have covered before, there are only two columns with missing values and they are exactly overlapping on the rows: 'days_employed' and 'total_income'. For the start, we most likely would want to find retired individuals and students values of 0 and work from there.

First, since it goes to follow that age is likely a strong predictor for total income, ages will be grouped in sets of 10 years, from 0 to 70+.

In [32]:
# Let's write a function that calculates the age category

def assign_age_group(age):
    if age < 0 or pd.isna(age):
        return 'NA'
    elif age < 10:
        return '0-9'
    elif age < 20:
        return '10-19'
    elif age < 30:
        return '20-29'
    elif age < 40:
        return '30-39'
    elif age < 50:
        return '40-49'
    elif age < 60:
        return '50-59'
    elif age < 70:
        return '60-69'
    else:
        return '70+'

In [33]:
# Test if the function works
data['dob_years'].apply(assign_age_group)

0        40-49
1        30-39
2        30-39
3        30-39
4        50-59
         ...  
21520    40-49
21521    60-69
21522    30-39
21523    30-39
21524    40-49
Name: dob_years, Length: 21231, dtype: object

In [34]:
# Creating new column based on function
data['age_group'] = data['dob_years'].apply(assign_age_group)

data.head(10)

children  days_employed  dob_years            education  education_id  \
0         1    8437.673028         42    bachelor's degree             0   
1         1    4024.803754         36  secondary education             1   
2         0    5623.422610         33  secondary education             1   
3         3    4124.747207         32  secondary education             1   
4         0    3402.660720         53  secondary education             1   
5         0     926.185831         27    bachelor's degree             0   
6         0    2879.202052         43    bachelor's degree             0   
7         0     152.779569         50  secondary education             1   
8         2    6929.865299         35    bachelor's degree             0   
9         0    2188.756445         41  secondary education             1   

       family_status  family_status_id gender income_type  debt  total_income  \
0            married                 0      F    employee     0     40620.102   
1            married                 0      F    employee     0     17932.802   
2            married                 0      M    employee     0     23341.752   
3            married                 0      M    employee     0     42820.568   
4  civil partnership                 1      F     retiree     0     25378.572   
5  civil partnership                 1      M    business     0     40922.170   
6            married                 0      F    business     0     38484.156   
7            married                 0      M    employee     0     21731.829   
8  civil partnership                 1      F    employee     0     15337.093   
9            married                 0      M    employee     0     23108.150   

                               purpose age_group  
0                purchase of the house     40-49  
1                         car purchase     30-39  
2                purchase of the house     30-39  
3              supplementary education     30-39  
4                    to have a wedding     50-59  
5                purchase of the house     20-29  
6                 housing transactions     40-49  
7                            education     50-59  
8                     having a wedding     30-39  
9  purchase of the house for my family     40-49

In [35]:
# Checking how values in the new column

data.groupby('age_group')['dob_years'].value_counts()

age_group  dob_years
10-19      19            14
20-29      29           542
           28           501
           27           490
           26           406
           25           356
           24           263
           23           250
           22           183
           21           110
           20            51
30-39      35           613
           34           595
           38           594
           33           577
           39           571
           31           555
           36           552
           30           533
           37           530
           32           505
40-49      40           601
           41           601
           42           591
           44           541
           48           534
           43           509
           49           505
           45           493
           47           477
           46           466
50-59      50           508
           52           483
           56           478
           54           473

To determine the income, we could seek out the data based on educational status and age group since those would be the most logical predictors of income. Generally, when making a judgment on income status, it will be better to measure based on median. The reason is simple, in that there are people who make significantly more or significantly less money than others. Another factor that might be possible would be to see if the data includes people likely to be home makers who might be working part-time, if at all.

While some factors may be connected, it might be easier to get a quick look at each one independently and see if they could singularly act as predictors. If the data set were much larger this would not be as practical, but to test across all the other values, we only need to check 6 pairwise.

In order to fill out the missing values, it is important to make a table without them to better perform analysis on the known values, to find good ways to predict them.

In [36]:
# Create a table without missing values and print a few of its rows to make sure it looks fine
no_missing_values = data.dropna()

no_missing_values.head(15)

children  days_employed  dob_years            education  education_id  \
0          1    8437.673028         42    bachelor's degree             0   
1          1    4024.803754         36  secondary education             1   
2          0    5623.422610         33  secondary education             1   
3          3    4124.747207         32  secondary education             1   
4          0    3402.660720         53  secondary education             1   
5          0     926.185831         27    bachelor's degree             0   
6          0    2879.202052         43    bachelor's degree             0   
7          0     152.779569         50  secondary education             1   
8          2    6929.865299         35    bachelor's degree             0   
9          0    2188.756445         41  secondary education             1   
10         2    4171.483647         36    bachelor's degree             0   
11         0     792.701887         40  secondary education             1   
13         0    1846.641941         54         some college             2   
14         0    1844.956182         56    bachelor's degree             0   
15         1     972.364419         26  secondary education             1   

        family_status  family_status_id gender income_type  debt  \
0             married                 0      F    employee     0   
1             married                 0      F    employee     0   
2             married                 0      M    employee     0   
3             married                 0      M    employee     0   
4   civil partnership                 1      F     retiree     0   
5   civil partnership                 1      M    business     0   
6             married                 0      F    business     0   
7             married                 0      M    employee     0   
8   civil partnership                 1      F    employee     0   
9             married                 0      M    employee     0   
10            married                 0      M    business     0   
11            married                 0      F    employee     0   
13            married                 0      F    employee     0   
14  civil partnership                 1      F    business     1   
15            married                 0      F    employee     0   

    total_income                              purpose age_group  
0      40620.102                purchase of the house     40-49  
1      17932.802                         car purchase     30-39  
2      23341.752                purchase of the house     30-39  
3      42820.568              supplementary education     30-39  
4      25378.572                    to have a wedding     50-59  
5      40922.170                purchase of the house     20-29  
6      38484.156                 housing transactions     40-49  
7      21731.829                            education     50-59  
8      15337.093                     having a wedding     30-39  
9      23108.150  purchase of the house for my family     40-49  
10     18230.959                      buy real estate     30-39  
11     12331.077           buy commercial real estate     40-49  
13     20873.317                         car purchase     50-59  
14     26420.466          buy residential real estate     50-59  
15     18691.345         construction of own property     20-29

In [37]:
# Look at the mean values for income based on your identified factors

print("Mean:", no_missing_values['total_income'].mean(), end='\n\n')

print(no_missing_values.groupby('education')['total_income'].mean(), end='\n\n')

print(no_missing_values.groupby('age_group')['total_income'].mean(), end='\n\n')

print(no_missing_values.groupby('family_status')['total_income'].mean(), end='\n\n')

print(no_missing_values.groupby('children')['total_income'].mean(), end='\n\n')

print(no_missing_values.groupby('income_type')['total_income'].mean(), end='\n\n')

print(no_missing_values.groupby('debt')['total_income'].mean(), end='\n\n')

print(no_missing_values.groupby('gender')['total_income'].mean())

Mean: 26799.003246370758

education
bachelor's degree      33197.258790
graduate degree        27960.024667
primary education      21144.882211
secondary education    24594.390815
some college           29034.211363
Name: total_income, dtype: float64

age_group
10-19    16993.942462
20-29    25585.600814
30-39    28314.525654
40-49    28575.427654
50-59    25807.707523
60-69    23236.985508
70+      20125.658331
Name: total_income, dtype: float64

family_status
civil partnership    26707.016264
divorced             27245.606570
married              27039.070983
unmarried            26983.707136
widow / widower      22998.392333
Name: total_income, dtype: float64

children
0    26430.072953
1    27405.559686
2    27489.198728
3    29366.910652
4    27289.829647
5    27268.847250
Name: total_income, dtype: float64

income_type
business                       32424.465009
civil servant                  27336.442546
employee                       25822.872585
entrepreneur                   

In [38]:
# Look at the median values for income based on your identified factors
print("Median:", no_missing_values['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('education')['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('age_group')['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('family_status')['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('children')['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('income_type')['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('debt')['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('gender')['total_income'].median(), end='\n\n')

print(no_missing_values.groupby('gender')['total_income'].std())

Median: 23203.328

education
bachelor's degree      28086.5425
graduate degree        25161.5835
primary education      18741.9760
secondary education    21832.2410
some college           25664.1810
Name: total_income, dtype: float64

age_group
10-19    14934.9010
20-29    22807.0365
30-39    24699.5815
40-49    24772.3820
50-59    22195.8470
60-69    19811.3260
70+      18751.3240
Name: total_income, dtype: float64

family_status
civil partnership    23199.2980
divorced             23687.2740
married              23369.8045
unmarried            23176.8360
widow / widower      20518.7285
Name: total_income, dtype: float64

children
0    23034.0880
1    23661.4030
2    23136.1155
3    25191.6190
4    24981.6340
5    29816.2255
Name: total_income, dtype: float64

income_type
business                       27598.5735
civil servant                  24076.1150
employee                       22815.1035
entrepreneur                   79866.1030
paternity / maternity leave     8612.6610
retire

This analysis will be tested on multiple categories. Since marital status and number of children likely has a connection, and age and education are also likely connected. So they will be checked again on these multiple factors.

In [39]:
# test for possible family status

family = ['family_status', 'children']

print('Mean income based on marriage and children status:')
print(no_missing_values.pivot_table(index=family, 
                                    values = 'total_income', 
                                    columns= 'gender', 
                                    aggfunc='mean', 
                                    margins=False))
print('Median income based on marriage and children status:')
print(no_missing_values.pivot_table(index=family, 
                                    values = 'total_income', 
                                    columns= 'gender', 
                                    aggfunc=['median', 'std'], 
                                    margins=False), end='\n\n')

print('Income based on age and education status:')
print(no_missing_values.pivot_table(index=['age_group', 'education'], 
                                    values = 'total_income', 
                                    aggfunc=['mean', 'median', 'std'], 
                                    margins=False))

Mean income based on marriage and children status:
gender                                 F             M        XNA
family_status     children                                       
civil partnership 0         25006.685058  29578.405501  32624.825
                  1         24706.132940  32451.872644        NaN
                  2         24603.293650  32847.852899        NaN
                  3         22501.396303  44397.153833        NaN
                  4         26723.865333  25210.974000        NaN
                  5         20176.344000           NaN        NaN
divorced          0         26096.476067  30721.209632        NaN
                  1         27104.597827  30420.839141        NaN
                  2         23548.585392  34514.304857        NaN
                  3         23311.777625  23294.830000        NaN
                  4         52885.145000           NaN        NaN
married           0         24390.426410  30738.418097        NaN
                  1      

To discuss the possible predictors, starting with ones that are not useful predictors:

Someone defaulting on a loan in the past does not seem to have a significant impact on their current income, nor generally does their number of children. Although families with exactly 3 children have higher incomes measured both in mean and median, and the median income of a 5-child household is also higher, but there are only 9 households with 5 children so it cannot be considered statistically significant.

Marital status does not generally have an impact on income, but widows/widowers have a noticeably lower income. Generally, as the number of children in a household increases from 0 to 3, women tend to make less money and men tend to make more money - which makes sense, a stay-at-home parent is more likely to be a mother. Women in general tend to have a slightly lower income, with a wider gap if the household has more children. Also, in most cases, households with 4 children have a noticeable dip in income.

Whether it is a marriage or a civil partnership, the earning power of an individual does not appear to change significantly, although widows and widowers have lower earnings than divorcees. The income of people measured across married, unmarried, and divorced is fairly consistent, though especially so among women. Men's earning power across those three categories fluctuates a little more but is still relatively close.

Suffice to say, there is a good reason to believe that measuring across the marital status, gender, and number of children in a household could be a useful predictor on a household income. However, this is not necessarily a perfect solution. The Standard Deviation across the data set is rather large, enough so that even an income of 0 would not be an outlier in many cases.

Age group and education are far more clear-cut in that it rises as a worker peaks and then drops as they reach older ages, and also that their average income rises as they have more education. These values may sometimes be less consistent than the familial status, though in examination they do appear to have some sort of patterns.

In both cases, filling things in with the median is a more practical choice. Due to the high standard deviation, it could be entirely suitable to simply fill all the empty values with the full data set's median income. Any sort of filler value we use could fluctuate wildly that it could also be a practical option to simply drop the missing values at this point. We would lose around 10% of the data set but there are tradeoffs if that 10% of the data is not present compared to if it is likely to be inaccurate.

Though we will not be dropping them for the purposes of this analysis, instead filling using filtered data that usually has lower standard deviation compared to the full data as well as comparable or lower standard deviation than the data filtered by gender, does say a better option would be to use medians after the data is filtered in some way. Thus, it is possible a suitable choice will be to choose our filler values across the entire data set based on the age group and education status.

In [40]:
#  Write a function that we will use for filling in missing values

# to test, a data frame will be made that creates a new column, 'median_income', to test a function that groups based on
# age_group and education

# this will be done in a new data frame so that it will be easier to check for errors before performing on the complete data

test_data = data.copy(deep=False)
test_data['median_income'] = data.groupby(['age_group', 'education'])['total_income'].transform(lambda x: x.fillna(x.median()))
test_data[test_data.isna().any(axis=1)]

children  days_employed  dob_years            education  education_id  \
12            0            NaN         65  secondary education             1   
26            0            NaN         41  secondary education             1   
29            0            NaN         63  secondary education             1   
41            0            NaN         50  secondary education             1   
55            0            NaN         54  secondary education             1   
...         ...            ...        ...                  ...           ...   
21489         2            NaN         47  secondary education             1   
21495         1            NaN         50  secondary education             1   
21497         0            NaN         48    bachelor's degree             0   
21502         1            NaN         42  secondary education             1   
21510         2            NaN         28  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
12     civil partnership                 1      M        retiree     0   
26               married                 0      M  civil servant     0   
29             unmarried                 4      F        retiree     0   
41               married                 0      F  civil servant     0   
55     civil partnership                 1      F        retiree     1   
...                  ...               ...    ...            ...   ...   
21489            married                 0      M       business     0   
21495  civil partnership                 1      F       employee     0   
21497            married                 0      F       business     0   
21502            married                 0      F       employee     0   
21510            married                 0      F       employee     0   

       total_income                   purpose age_group  median_income  
12              NaN         to have a wedding     60-69      18873.764  
26              NaN                 education     40-49      23001.785  
29              NaN    building a real estate     60-69      18873.764  
41              NaN  second-hand car purchase     50-59      21220.535  
55              NaN         to have a wedding     50-59      21220.535  
...             ...                       ...       ...            ...  
21489           NaN         purchase of a car     40-49      23001.785  
21495           NaN          wedding ceremony     50-59      21220.535  
21497           NaN       building a property     40-49      30298.713  
21502           NaN    building a real estate     40-49      23001.785  
21510           NaN              car purchase     20-29      21176.780  

[2081 rows x 14 columns]

In [41]:
# Check if it works

data['total_income'] = data.groupby(['age_group', 'education'])['total_income'].transform(lambda x: x.fillna(x.median()))
data

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0    3402.660720         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0    3439.374041         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose age_group  
0         40620.102    purchase of the house     40-49  
1         17932.802             car purchase     30-39  
2         23341.752    purchase of the house     30-39  
3         42820.568  supplementary education     30-39  
4         25378.572        to have a wedding     50-59  
...             ...                      ...       ...  
21520     35966.698     housing transactions     40-49  
21521     24959.969        purchase of a car     60-69  
21522     14347.610                 property     30-39  
21523     39054.888        buying my own car     30-39  
21524     13127.587             to buy a car     40-49  

[21231 rows x 13 columns]

In [42]:
# check for null values
data['total_income'].isna().value_counts()

False    21231
Name: total_income, dtype: int64

###  Restoring values in `days_employed`

For length of employment, it initially appears that a mean would be a more accurate choice to restore missing values. The reason for this being that generally, it is expected that jobs can and often do have high turnover rates, regardless of other outcomes. Most likely, when we take the median, it will be significantly lower than the mean.

It also could be hypothesized that the most relevant factor by far will be the age group, as of course there is a hard cap on how long someone can be employed based specifically on their age. Their education will likely also be relevant, and their marital status may be slightly significant. For singular analysis, there are few enough factors to not test across all of them for a quick initial look.

In [43]:
# Distribution of `days_employed` medians based on your identified parameters

print("Median:", no_missing_values['days_employed'].median(), "\n"
     "Std:",  no_missing_values['days_employed'].std(), end='\n\n')

print(no_missing_values.groupby('education')['days_employed'].median(), end='\n\n')

print(no_missing_values.groupby('age_group')['days_employed'].median(), end='\n\n')

print(no_missing_values.groupby('family_status')['days_employed'].median(), end='\n\n')

print(no_missing_values.groupby('children')['days_employed'].median(), end='\n\n')

print(no_missing_values.groupby('income_type')['days_employed'].median(), end='\n\n')

print(no_missing_values.groupby('debt')['days_employed'].median(), end='\n\n')

print(no_missing_values.groupby('gender')['days_employed'].median())

Median: 2197.610391933402 
Std: 2149.4384845609616

education
bachelor's degree      1896.569279
graduate degree        3569.305175
primary education      3043.933615
secondary education    2393.978448
some college           1210.909349
Name: days_employed, dtype: float64

age_group
10-19     724.492610
20-29    1007.207074
30-39    1601.919871
40-49    2112.694563
50-59    3434.808702
60-69    3628.436183
70+      3652.129894
Name: days_employed, dtype: float64

family_status
civil partnership    1947.761961
divorced             2398.424010
married              2308.492225
unmarried            1461.758857
widow / widower      3554.549701
Name: days_employed, dtype: float64

children
0    2625.852176
1    1666.838773
2    1683.917531
3    1734.879824
4    1905.879025
5    1231.571486
Name: days_employed, dtype: float64

income_type
business                       1556.150678
civil servant                  2672.903939
employee                       1573.791064
entrepreneur               

In [44]:
# Distribution of `days_employed` means based on your identified parameters
print("Mean:", no_missing_values['days_employed'].mean(), end='\n\n')

print(no_missing_values.groupby('education')['days_employed'].mean(), end='\n\n')

print(no_missing_values.groupby('age_group')['days_employed'].mean(), end='\n\n')

print(no_missing_values.groupby('family_status')['days_employed'].mean(), end='\n\n')

print(no_missing_values.groupby('children')['days_employed'].mean(), end='\n\n')

print(no_missing_values.groupby('income_type')['days_employed'].mean(), end='\n\n')

print(no_missing_values.groupby('debt')['days_employed'].mean(), end='\n\n')

print(no_missing_values.groupby('gender')['days_employed'].mean())

Mean: 2585.412900432714

education
bachelor's degree      2431.165867
graduate degree        3536.559416
primary education      2540.081375
secondary education    2684.169887
some college           1671.195584
Name: days_employed, dtype: float64

age_group
10-19     633.678086
20-29    1216.823432
30-39    2035.879026
40-49    2758.989760
50-59    3403.599812
60-69    3691.642639
70+      3731.259123
Name: days_employed, dtype: float64

family_status
civil partnership    2470.040055
divorced             2659.662842
married              2671.026190
unmarried            2074.058152
widow / widower      3384.050437
Name: days_employed, dtype: float64

children
0    2774.831110
1    2249.459122
2    2145.137153
3    2204.802409
4    2233.272666
5    1432.348601
Name: days_employed, dtype: float64

income_type
business                       2119.565621
civil servant                  3392.119263
employee                       2325.740892
entrepreneur                    520.848083
paternity /

As expected, the medians are noticeably lower than the means. Whether the proposed explanation is true or not is not particularly relevant for our purposes at the moment. Regardless, for both the mean and the median there is a massive range of days employed across most distinctions (usually having some entries be under 1000 and others being nearly 4000). This could suggest that the mean is a better choice to use here.

In particular, this is because the clearest pattern we see on the data is by taking the mean value of the data grouped by the ages. It has a steady increase of around 700 in each age group until the groups of 60-69 and 70+ (when we will see more retirees).

None of the questions that we seek to answer directly involve the number of days employed, so it generally will be less harmful to be a little less thorough when filling out this data.

In [45]:
# Let's write a function that calculates means or medians (depending on your decision) based on your identified parameter
test_data = data.copy(deep=False)
test_data['mean_days'] = data.groupby('age_group')['days_employed'].transform(lambda x: x.fillna(x.median()))
test_data[test_data.isna().any(axis=1)]

children  days_employed  dob_years            education  education_id  \
12            0            NaN         65  secondary education             1   
26            0            NaN         41  secondary education             1   
29            0            NaN         63  secondary education             1   
41            0            NaN         50  secondary education             1   
55            0            NaN         54  secondary education             1   
...         ...            ...        ...                  ...           ...   
21489         2            NaN         47  secondary education             1   
21495         1            NaN         50  secondary education             1   
21497         0            NaN         48    bachelor's degree             0   
21502         1            NaN         42  secondary education             1   
21510         2            NaN         28  secondary education             1   

           family_status  family_status_id gender    income_type  debt  \
12     civil partnership                 1      M        retiree     0   
26               married                 0      M  civil servant     0   
29             unmarried                 4      F        retiree     0   
41               married                 0      F  civil servant     0   
55     civil partnership                 1      F        retiree     1   
...                  ...               ...    ...            ...   ...   
21489            married                 0      M       business     0   
21495  civil partnership                 1      F       employee     0   
21497            married                 0      F       business     0   
21502            married                 0      F       employee     0   
21510            married                 0      F       employee     0   

       total_income                   purpose age_group    mean_days  
12        18873.764         to have a wedding     60-69  3628.436183  
26        23001.785                 education     40-49  2112.694563  
29        18873.764    building a real estate     60-69  3628.436183  
41        21220.535  second-hand car purchase     50-59  3434.808702  
55        21220.535         to have a wedding     50-59  3434.808702  
...             ...                       ...       ...          ...  
21489     23001.785         purchase of a car     40-49  2112.694563  
21495     21220.535          wedding ceremony     50-59  3434.808702  
21497     30298.713       building a property     40-49  2112.694563  
21502     23001.785    building a real estate     40-49  2112.694563  
21510     21176.780              car purchase     20-29  1007.207074  

[2081 rows x 14 columns]

In [46]:
# Apply function

data['days_employed'] = data.groupby('age_group')['days_employed'].transform(lambda x: x.fillna(x.median()))
data

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0    3402.660720         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0    3439.374041         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income                  purpose age_group  
0         40620.102    purchase of the house     40-49  
1         17932.802             car purchase     30-39  
2         23341.752    purchase of the house     30-39  
3         42820.568  supplementary education     30-39  
4         25378.572        to have a wedding     50-59  
...             ...                      ...       ...  
21520     35966.698     housing transactions     40-49  
21521     24959.969        purchase of a car     60-69  
21522     14347.610                 property     30-39  
21523     39054.888        buying my own car     30-39  
21524     13127.587             to buy a car     40-49  

[21231 rows x 13 columns]

In [47]:
# Check if function worked

data['days_employed'].isna().value_counts()

False    21231
Name: days_employed, dtype: int64

## Categorization of data

Now we should categorize the data, where necessary, to make analysis simpler.

Most notably, we should have as few entries in the "purpose" column as we can, within reason. From the exposure of loans we can get from a quick glance over portions of the data, house purchases, car purchase, real estate, wedding, and education are the most common purposes given.

The numerical data of the total income is also useful to categorize. If we wished to do something such as create a linear model, it would be fine to work with the data as-is. However, we are simply looking for correlations and patterns. We will get an immense amount of unique points if we do that with our data set. Categorizing the numerical data is a quick solution.

In [48]:
# Print the values for your selected data for categorization
data['purpose'].unique()

array(['purchase of the house', 'car purchase', 'supplementary education',
       'to have a wedding', 'housing transactions', 'education',
       'having a wedding', 'purchase of the house for my family',
       'buy real estate', 'buy commercial real estate',
       'buy residential real estate', 'construction of own property',
       'property', 'building a property', 'buying a second-hand car',
       'buying my own car', 'transactions with commercial real estate',
       'building a real estate', 'housing',
       'transactions with my real estate', 'cars', 'to become educated',
       'second-hand car purchase', 'getting an education', 'car',
       'wedding ceremony', 'to get a supplementary education',
       'purchase of my own house', 'real estate transactions',
       'getting higher education', 'to own a car', 'purchase of a car',
       'profile education', 'university education',
       'buying property for renting out', 'to buy a car',
       'housing renovation', 'going

These include a few things that might be a bit different, such as "renovation". To get a better idea of if renovation might be better to include in an "other" section, if there are some that have a small number of entries.

In [49]:
# Check the unique values
data['purpose'].value_counts()

wedding ceremony                            785
having a wedding                            759
to have a wedding                           755
real estate transactions                    669
buy commercial real estate                  655
buying property for renting out             647
transactions with commercial real estate    643
housing transactions                        641
purchase of the house for my family         636
housing                                     635
purchase of the house                       634
property                                    627
construction of own property                626
transactions with my real estate            623
building a property                         619
purchase of my own house                    618
building a real estate                      617
buy real estate                             613
housing renovation                          602
buy residential real estate                 599
buying my own car                       

In this group, we can see values that could be classed as:

'wedding' ('wedding ceremony', 'having a wedding', 'to have a wedding')

'house purchase' ('housing transactions', 'purchase of the house for my family', 'housing', 'purchase of the house', 'purchase of my own house')

'real estate' ('real estate transactions', 'buy commercial real estate', 'transactions with commercial real estate', 'buy residential real estate', 'transactions with my real estate', 'buy real estate')

'car purchase' ('buying my own car', 'car', 'second-hand car purchase', 'cars', 'buying a second-hand car', 'to own a car', 'to buy a car', 'car purchase', 'purchase of a car')

'education' ('going to university', 'supplementary education', 'university education', 'to get a supplementary education', 'education', 'getting an education', 'profile education', 'getting higher education', 'to become educated')

The remaining values are a little vague and could be in one of multiple categories depending on the details. I think that one clean-cut category would be 'construction / renovation' ('construction of own property', 'building a property', 'building a real estate', 'housing renovation'). Vague ones are 'buying property for renting out' and 'property' which could be under either 'house purchase' or 'real estate'.

In this case, 'buying property for renting out' will be placed into 'real estate' and the 'property' will be put into 'house purchase'.

In [50]:
# Let's write a function to categorize the data based on common topics
def categorize_data(x):
    wedding = ['wedding ceremony', 'having a wedding', 'to have a wedding', 'wedding']
    house_purchase = ['housing transactions', 'purchase of the house for my family', 'housing', 'purchase of the house', 
                      'purchase of my own house', 'property', 'house_purchase']
    real_estate = ['real estate transactions', 'buy commercial real estate', 'transactions with commercial real estate', 
                   'buy residential real estate', 'transactions with my real estate', 'buy real estate', 
                   'buying property for renting out', 'real_estate']
    car_purchase = ['buying my own car', 'car', 'second-hand car purchase', 'cars', 'buying a second-hand car', 'to own a car', 
                    'to buy a car', 'car purchase', 'purchase of a car', 'car_purchase']
    education = ['going to university', 'supplementary education', 'university education', 'to get a supplementary education', 
                 'education', 'getting an education', 'profile education', 'getting higher education', 'to become educated']
    construction_renovation = ['construction of own property', 'building a property', 'building a real estate', 
                               'housing renovation', 'construction_renovation']
    if x['purpose'] in wedding:
        return 'wedding'
    if x['purpose'] in house_purchase:
        return 'house_purchase'
    if x['purpose'] in real_estate:
        return 'real_estate'
    if x['purpose'] in car_purchase:
        return 'car_purchase'
    if x['purpose'] in education:
        return 'education'
    if x['purpose'] in construction_renovation:
        return 'construction_renovation'

In [51]:
# Create a column with the categories and count the values for them

data['purpose'] = data.apply(categorize_data, axis = 1)
data

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0    3402.660720         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0    3439.374041         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income         purpose age_group  
0         40620.102  house_purchase     40-49  
1         17932.802    car_purchase     30-39  
2         23341.752  house_purchase     30-39  
3         42820.568       education     30-39  
4         25378.572         wedding     50-59  
...             ...             ...       ...  
21520     35966.698  house_purchase     40-49  
21521     24959.969    car_purchase     60-69  
21522     14347.610  house_purchase     30-39  
21523     39054.888    car_purchase     30-39  
21524     13127.587    car_purchase     40-49  

[21231 rows x 13 columns]

Since we are going to be doing some simple descriptive statistics, categorizing the numerical data will make it more easy to read. If we wish to do more in-depth statistics such as linear regression, keeping the numerical data would be required but for the current purpose it is better to make categories.

We are not working with days_employed, but if we were then categorizing that would be something to do. Instead, 'total_income' is the variable we should categorize by separating it into groups. Most likely a good way to separate would be in sets of 10,000 but based on the appearance of the data it might be better to do it in a different way. We shall check what the total_income data looks like to determine how to categorize.

In [52]:
# Looking through all the numerical data in your selected column for categorization
data['total_income'].describe()

count     21231.000000
mean      26477.600107
std       15748.933187
min        3306.762000
25%       17197.758500
50%       23001.785000
75%       31329.465500
max      362496.645000
Name: total_income, dtype: float64

It is clear here that there are some extremely high outliers in this column. The max is over 10 times higher than the third quartile. Based on the median and the standard deviation, 95% of all the data falls between 3306.762000 (the minimum on the entire data set) and 54499.651374. So rather than groups of 10,000, we could get more robust analysis if we split in sets of 5,000. This will give us 95% of our data in 11 groups, which will be useful to scan for patterns.

In [53]:
# Creating column with categories

data['income_rank'] = round(data['total_income']/5000)
data

children  days_employed  dob_years            education  education_id  \
0             1    8437.673028         42    bachelor's degree             0   
1             1    4024.803754         36  secondary education             1   
2             0    5623.422610         33  secondary education             1   
3             3    4124.747207         32  secondary education             1   
4             0    3402.660720         53  secondary education             1   
...         ...            ...        ...                  ...           ...   
21520         1    4529.316663         43  secondary education             1   
21521         0    3439.374041         67  secondary education             1   
21522         1    2113.346888         38  secondary education             1   
21523         3    3112.481705         38  secondary education             1   
21524         2    1984.507589         40  secondary education             1   

           family_status  family_status_id gender income_type  debt  \
0                married                 0      F    employee     0   
1                married                 0      F    employee     0   
2                married                 0      M    employee     0   
3                married                 0      M    employee     0   
4      civil partnership                 1      F     retiree     0   
...                  ...               ...    ...         ...   ...   
21520  civil partnership                 1      F    business     0   
21521            married                 0      F     retiree     0   
21522  civil partnership                 1      M    employee     1   
21523            married                 0      M    employee     1   
21524            married                 0      F    employee     0   

       total_income         purpose age_group  income_rank  
0         40620.102  house_purchase     40-49          8.0  
1         17932.802    car_purchase     30-39          4.0  
2         23341.752  house_purchase     30-39          5.0  
3         42820.568       education     30-39          9.0  
4         25378.572         wedding     50-59          5.0  
...             ...             ...       ...          ...  
21520     35966.698  house_purchase     40-49          7.0  
21521     24959.969    car_purchase     60-69          5.0  
21522     14347.610  house_purchase     30-39          3.0  
21523     39054.888    car_purchase     30-39          8.0  
21524     13127.587    car_purchase     40-49          3.0  

[21231 rows x 14 columns]

In [54]:
# Count each categories values to see the distribution
data['income_rank'].value_counts().sort_index()

1.0      255
2.0     1815
3.0     3452
4.0     4303
5.0     3976
6.0     2621
7.0     1535
8.0     1019
9.0      741
10.0     398
11.0     330
12.0     209
13.0     151
14.0     103
15.0      72
16.0      56
17.0      40
18.0      28
19.0      20
20.0      13
21.0      17
22.0      19
23.0       8
24.0       5
25.0       2
26.0       4
27.0       5
28.0       3
29.0       3
31.0       2
32.0       3
33.0       2
34.0       1
35.0       5
36.0       1
38.0       1
39.0       1
40.0       1
41.0       2
43.0       1
46.0       1
50.0       1
51.0       1
55.0       3
70.0       1
72.0       1
Name: income_rank, dtype: int64

We can see here that even though 95% of our data is in the first 11 groups, there are still quite a few entries in the next few groups. It doesn't begin to truly taper off until we approach around group 25 (125,000 income) but even then there are entries in most of the groups until 55 (income of 275,000) where it then jumps to group 70 (350,000).

This makes sense, as not only are there fewer wealthy people in general, they also should be less likely to be applying for loans - at least, for the purposes that we see given in the data set.

## Checking the Hypotheses


**Is there a correlation between having children and paying back on time?**

In [55]:
# Check the children data and paying back on time

print("Correlation of 'debt' and 'children':", data['debt'].corr(data['children']), end='\n\n')

# Calculating default-rate based on the number of children

pd.pivot_table(data, columns='debt', values='gender', index='children', aggfunc='count', margins=True)

Correlation of 'debt' and 'children': 0.024958000127971815



debt            0       1    All
children                        
0         12964.0  1058.0  14022
1          4351.0   441.0   4792
2          1845.0   194.0   2039
3           301.0    27.0    328
4            37.0     4.0     41
5             9.0     NaN      9
All       19507.0  1724.0  21231

**Conclusion**

Checking a pivot table for purely checking the rate of defaulting in each group in the "children" value, we see fairly consistent values. In order of 0 to 5 children, the percent of loans that were not paid back on time are as follows: 7.5453%, 9.2028%, 9.5145%, 8.2317%, 9.7561%, 0%.

Disregarding the 0% for 5 children, as the sample size was obviously too small, we see that there is a slightly higher rate of defaulting for those with children, but it is very close to the rate of those without children.

Running a simple correlation algorithm, we receive a value of approximately 0.02496 between "debt" and "children". This means that there is almost no correlation between the number of children in a family and their ability to pay back a loan.

**Is there a correlation between family status and paying back on time?**

In [56]:
# Check the family status data and paying back on time

print("Correlation of 'debt' and 'family_status_id':", data['debt'].corr(data['family_status_id']), end='\n\n')

# Calculating default-rate based on family status

pd.pivot_table(data, columns='debt', values='gender', index='family_status', aggfunc='count', margins=True)

Correlation of 'debt' and 'family_status_id': 0.020530792656592012



debt                   0     1    All
family_status                        
civil partnership   3730   383   4113
divorced            1095    84   1179
married            11290   923  12213
unmarried           2508   272   2780
widow / widower      884    62    946
All                19507  1724  21231

**Conclusion**

The rates of defaulting on the loan based on family status are as follows: Unmarried = 9.7842%, Civil Partnership = 9.3119%, Married = 7.5575%, Divorced = 7.1247%, Widow/widower = 6.5539% with a total rate of 8.1202%, and a correlation rate of 0.0205 (another case of almost no correlation). These numbers look similar to the previous ones, although they are a little lower.

It does not appear that there is a large correlation between the family status and paying a loan back on time. Analyzing the family status along with the number of children, though, is something that should be examined. As we can see, there is a low rate of defaulting among married couples (and, oddly, divorcees and widows/widowers have even lower rates, when one would think that given their general lower income that they should be more likely to be unable to repay a loan).

This seems a little odd if we consider that, based on children = 0 having the highest rate of paying back loans, we would expect unmarried people to not have the highest rate of defaulting. It may be in our best interest to examine how the two interact.

In [57]:
pd.pivot_table(data, columns='debt', values='gender', index=['family_status', 'children'], aggfunc='count', margins=True)

debt                              0       1    All
family_status     children                        
civil partnership 0          2490.0   227.0   2717
                  1           871.0   118.0    989
                  2           311.0    30.0    341
                  3            48.0     8.0     56
                  4             8.0     NaN      8
                  5             2.0     NaN      2
divorced          0           722.0    55.0    777
                  1           290.0    21.0    311
                  2            72.0     7.0     79
                  3            10.0     1.0     11
                  4             1.0     NaN      1
married           0          6923.0   514.0   7437
                  1          2724.0   244.0   2968
                  2          1380.0   145.0   1525
                  3           230.0    17.0    247
                  4            26.0     3.0     29
                  5             7.0     NaN      7
unmarried         0          2039.0   210.0   2249
                  1           396.0    51.0    447
                  2            65.0     9.0     74
                  3             7.0     1.0      8
                  4             1.0     1.0      2
widow / widower   0           790.0    52.0    842
                  1            70.0     7.0     77
                  2            17.0     3.0     20
                  3             6.0     NaN      6
                  4             1.0     NaN      1
All                         19507.0  1724.0  21231

This pivot table does contain a wider range of defaulting rates and does provide some logical results (such as married people having the lower rates of defaulting on loans) but largely it has only widened the gap, from around 7-9% to approximately 6-11% (with a couple of ratios reaching around 15% in data points with fewer observations). Splitting in this manner does seem to show a slightly higher correlation, but even so, it is rather minor.

**Is there a correlation between income level and paying back on time?**

In [58]:
# Check the income level data and paying back on time
print("Correlation of 'debt' and 'total_income':", data['debt'].corr(data['total_income']))
print("Correlation of 'debt' and 'income_rank':", data['debt'].corr(data['income_rank']), end='\n\n')

# Calculating default-rate based on income level

pd.pivot_table(data, columns='debt', values='gender', index='income_rank', aggfunc='count', margins=True)

Correlation of 'debt' and 'total_income': -0.013064282392381285
Correlation of 'debt' and 'income_rank': -0.012824455029007956



debt               0       1    All
income_rank                        
1.0            238.0    17.0    255
2.0           1679.0   136.0   1815
3.0           3160.0   292.0   3452
4.0           3938.0   365.0   4303
5.0           3612.0   364.0   3976
6.0           2410.0   211.0   2621
7.0           1422.0   113.0   1535
8.0            950.0    69.0   1019
9.0            693.0    48.0    741
10.0           368.0    30.0    398
11.0           301.0    29.0    330
12.0           193.0    16.0    209
13.0           141.0    10.0    151
14.0            97.0     6.0    103
15.0            69.0     3.0     72
16.0            53.0     3.0     56
17.0            37.0     3.0     40
18.0            27.0     1.0     28
19.0            20.0     NaN     20
20.0            10.0     3.0     13
21.0            17.0     NaN     17
22.0            19.0     NaN     19
23.0             7.0     1.0      8
24.0             5.0     NaN      5
25.0             2.0     NaN      2
26.0             3.0     1.0      4
27.0             5.0     NaN      5
28.0             2.0     1.0      3
29.0             3.0     NaN      3
31.0             2.0     NaN      2
32.0             3.0     NaN      3
33.0             1.0     1.0      2
34.0             1.0     NaN      1
35.0             5.0     NaN      5
36.0             1.0     NaN      1
38.0             1.0     NaN      1
39.0             1.0     NaN      1
40.0             1.0     NaN      1
41.0             2.0     NaN      2
43.0             1.0     NaN      1
46.0             1.0     NaN      1
50.0             1.0     NaN      1
51.0             1.0     NaN      1
55.0             3.0     NaN      3
70.0             NaN     1.0      1
72.0             1.0     NaN      1
All          19507.0  1724.0  21231

**Conclusion**

In this case, we see that the correlation is still fairly weak, though in some cases there does appear to be different results. The rates of defaulting still are estimating to around 7-9%, which is the same as our previous tests and still close to our unfiltered defaulting rate of 8.1202%. However, in this case we do see a pattern that is completely unsurprising: As total_income rises, the rate of people who have failed to repay a loan steadily drops.

There are some higher rates of defaulting in the lowest couple income brackets, which tells me there might be possibly different results if the income rank is made wider. For that purpose, we will test again where income ranks are separated by 10,000 and 15,000 rather than the current 5,000.

In [59]:
# separating income rank by 10000

data['income_rank'] = round(data['total_income']/10000)

print("Correlation of 'debt' and 'income_rank':", data['debt'].corr(data['income_rank']), end='\n\n')

# Calculating default-rate based on income level

pd.pivot_table(data, columns='debt', values='gender', index='income_rank', aggfunc='count', margins=True)

Correlation of 'debt' and 'income_rank': -0.013568627126992236



debt               0       1    All
income_rank                        
0.0             24.0     2.0     26
1.0           3385.0   295.0   3680
2.0           7713.0   732.0   8445
3.0           4649.0   407.0   5056
4.0           2027.0   156.0   2183
5.0            839.0    70.0    909
6.0            406.0    33.0    439
7.0            192.0    13.0    205
8.0            110.0     6.0    116
9.0             56.0     2.0     58
10.0            28.0     3.0     31
11.0            29.0     1.0     30
12.0             9.0     NaN      9
13.0             6.0     1.0      7
14.0             6.0     1.0      7
15.0             4.0     NaN      4
16.0             4.0     1.0      5
17.0             4.0     NaN      4
18.0             3.0     NaN      3
19.0             1.0     NaN      1
20.0             3.0     NaN      3
21.0             1.0     NaN      1
22.0             1.0     NaN      1
23.0             1.0     NaN      1
25.0             1.0     NaN      1
26.0             1.0     NaN      1
27.0             2.0     NaN      2
28.0             1.0     NaN      1
35.0             NaN     1.0      1
36.0             1.0     NaN      1
All          19507.0  1724.0  21231

In [60]:
# separating income rank by 15000

data['income_rank'] = round(data['total_income']/15000)

print("Correlation of 'debt' and 'income_rank':", data['debt'].corr(data['income_rank']), end='\n\n')

# Calculating default-rate based on income level

pd.pivot_table(data, columns='debt', values='gender', index='income_rank', aggfunc='count', margins=True)

Correlation of 'debt' and 'income_rank': -0.011109358541784575



debt               0       1    All
income_rank                        
0.0            238.0    17.0    255
1.0           8777.0   793.0   9570
2.0           7444.0   688.0   8132
3.0           2011.0   147.0   2158
4.0            635.0    55.0    690
5.0            219.0    12.0    231
6.0             84.0     4.0     88
7.0             46.0     3.0     49
8.0             14.0     1.0     15
9.0             10.0     2.0     12
10.0             5.0     NaN      5
11.0             5.0     1.0      6
12.0             6.0     NaN      6
13.0             3.0     NaN      3
14.0             3.0     NaN      3
15.0             1.0     NaN      1
17.0             2.0     NaN      2
18.0             3.0     NaN      3
23.0             NaN     1.0      1
24.0             1.0     NaN      1
All          19507.0  1724.0  21231

Separating the data with wider margins does show the same patterns. It appears a little less clear since the rates fluctuate more, the points where they switch are a bit harder to notice. We will thus return the income_rank to being separated by values of 5000.

In [61]:
data['income_rank'] = round(data['total_income']/5000)

**How does credit purpose affect the default rate?**

In [62]:
# Check the percentages for default rate for each credit purpose and analyze them

pd.pivot_table(data, columns='debt', values='gender', index='purpose', aggfunc='count', margins=True)

debt                         0     1    All
purpose                                    
car_purchase              3861   397   4258
construction_renovation   2286   178   2464
education                 3601   369   3970
house_purchase            3531   260   3791
real_estate               4110   339   4449
wedding                   2118   181   2299
All                      19507  1724  21231

**Conclusion**

Our percentages are as follows: Car purchase = 9.3236%, construction/renovation = 7.2240%, education = 9.2947%, house purchase = 6.8583%, real estate = 7.6197%, wedding = 7.8730%.

Car purchase and education being slightly higher makes sense, as those would tend to be loans taken out by someone who is younger and may not be as financially stable, so they probably are more liable to default on their loan. Weddings, purchases of property, and renovation are things that generally people undergo when they are already in a position where they are actively making money, and they are able to budget accordingly.

To see how this works, we will generate a second pivot table that includes the age group. We should suspect that for the younger groups in general, the rate of default should be higher.

In [63]:
pd.pivot_table(data, columns='debt', values='gender', index=['purpose', 'age_group'], aggfunc='count', margins=True)

debt                                     0       1    All
purpose                 age_group                        
car_purchase            10-19          3.0     NaN      3
                        20-29        517.0    76.0    593
                        30-39        996.0   134.0   1130
                        40-49        990.0    90.0   1080
                        50-59        865.0    65.0    930
                        60-69        460.0    28.0    488
                        70+           30.0     4.0     34
construction_renovation 10-19          1.0     NaN      1
                        20-29        351.0    36.0    387
                        30-39        588.0    58.0    646
                        40-49        590.0    39.0    629
                        50-59        487.0    34.0    521
                        60-69        250.0    10.0    260
                        70+           19.0     1.0     20
education               10-19          1.0     NaN      1
                        20-29        522.0    78.0    600
                        30-39        921.0   117.0   1038
                        40-49        891.0    81.0    972
                        50-59        815.0    65.0    880
                        60-69        419.0    28.0    447
                        70+           32.0     NaN     32
house_purchase          20-29        505.0    58.0    563
                        30-39        956.0    79.0   1035
                        40-49        888.0    55.0    943
                        50-59        770.0    47.0    817
                        60-69        385.0    20.0    405
                        70+           27.0     1.0     28
real_estate             10-19          5.0     1.0      6
                        20-29        603.0    68.0    671
                        30-39       1054.0   100.0   1154
                        40-49       1026.0    94.0   1120
                        50-59        931.0    57.0    988
                        60-69        455.0    19.0    474
                        70+           36.0     NaN     36
wedding                 10-19          3.0     NaN      3
                        20-29        306.0    32.0    338
                        30-39        562.0    60.0    622
                        40-49        532.0    42.0    574
                        50-59        460.0    35.0    495
                        60-69        236.0    12.0    248
                        70+           19.0     NaN     19
All                                19507.0  1724.0  21231

Here we see that regardless of the purpose, the age groups do have a clear correlation with the rate of loan repayment.

# General Conclusion 

If there were any issues within the data set, it may be that there was a flaw in how the missing values were filled out. They were done so with very simple methodology that largely was looking only at a couple predictors, for ranges of numbers that were incredibly volatile.

From this point, we can say that even if there is a predictive effect that these factors have on whether or not someone will repay a loan, the effect is fairly small. In a largescale scenario, checking for someone's marital status, number of children, income level, or purpose for applying to a loan do seem to have an influence on whether or not they will default, however, the effect they do have in such situations is rather small.

For a high-risk industry, however, it is suitable to use these small discrepancies as predictors. The results do appear to make logical sense as means to help predict a person's ability to repay a loan. Combining the number of children with the martial status makes a better estimate for that segment. The reason for taking out a loan may be better to analyze when taken in account with the age group of an individual.

Interestingly, there is not much indication that the income level is a strong predictor of if one is able to pay back their loan. The default rate shown in the data set fluctuates a bit too much without a clear pattern. This may be a lack of information - the amount provided in the loan would be a good factor to account for, as well. Even if the purpose is the same, the amount loaned out is important. For instance, if two people are both attempting to take a loan for a car purchase, where one of them has an income of 15,000 and seeking a loan for a \\$20,000 used car and one holds an income of 30,000 but is seeking a loan for a \\$50,000 new car, it will be easier for the lower income person to pay back the loan. Additionally, 'total_income' does not appear to account for a household income, but only individual income.